### PR TITLE
Adds start page and sets up providers.

### PR DESCRIPTION
**Pull request by wisplite**
This branch sets up all the providers for language and color, and it adds the start page with the title, tagline, account buttons, and language switcher. This branch also creates the new, less confusing project formatting, and adds the first comments in our entire app :)

### CODE REVIEW

**Comment by wisplite** [comment]
Just added a commit that changes the language names from their English versions to the versions in their respective languages.

Having a language switcher where are the languages are listed in English is really funny though

**Comment by sniveeey** [comment]
nuh uh

**Review by sniveeey — APPROVED** [review]

**Review by AAMP612 — COMMENTED** [review]
Good job

**Review by AAMP612 — APPROVED** [review]
yippee

**Comment by wisplite** [comment]
This branch cost me my computer, it better be worth it.

**Pull request merged**
